name: animephilic
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6
  http: ^1.4.0
  webview_flutter: ^4.11.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  meta: ^1.16.0
  shared_preferences: ^2.5.3
  font_awesome_flutter: ^10.8.0
  sqflite: ^2.4.2
  path: ^1.9.1
  fl_chart: ^0.71.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/avatar.png
